export type Cancion = {
  numero: number;
  titulo: string;
  artista: string;
  youtubeId: string;
  letra: string;
};

export const LISTA_CANCIONES = [
  "Jennifer Lopez - Una Noche Más",
  "W Sound Beéle Westcol Ovy On The Drums - La Plena",
  "Figa Flawas - La Marina Sta Morena",
  "Melody - Esa Diva",
  "HUGEL - Una Noche con Hugel",
  "Vilu Gontero - Capaz vs We Found Love Mashup",
  "María Isabel - Antes Muerta Que Sencilla",
  "Culture Beat - Mr. Vain",
  "Dani Fernández - Me Has Invitado a Bailar",
  "KAROL G - Si Antes Te Hubiera Conocido",
  "Lola Indigo - La Reina",
  "Gusanito - Vive La Vida",
  "Nebulossa - Zorra",
  "El Último de la Fila - Cuando el Mar te Tenga",
  "C Tangana - Mala Mujer",
  "Luck Ra BM - La Morocha",
  "Daddy Yankee - Gasolina",
  "Sebastián Yatra Manuel Turizo Beéle - Vagabundo",
  "Marshmello Manuel Turizo - El Merengue",
  "The Tyets - Coti x Coti",
  "Vicco - Nochentera",
  "Juan Luis Guerra - La Bilirrubina",
  "sangiovanni Aitana - Mariposas",
  "Zzoilo Aitana - Mon Amour Remix",
  "Bad Bunny - Tití Me Preguntó",
  "El Canto del Loco - Zapatillas",
  "Sebastián Yatra - Tacones Rojos",
  "Starship - Nothing's Gonna Stop Us Now",
  "Farruko - Pepas",
  "Rauw Alejandro - Todo de Ti",
  "Camela - Cuando Zarpa el Amor",
  "Merche - Abre Tu Mente",
  "Corona - The Rhythm of the Night",
  "Mecano - Me Colé en una Fiesta",
  "Daniela Romo - Yo No Te Pido La Luna",
  "La Guardia - Cuando Brille el Sol",
  "Raffaella Carrà - Hay Que Venir al Sur",
  "Alaska y Dinarama - A Quién Le Importa",
  "Camilo Sesto - Vivir Así es Morir de Amor",
  "Fred De Palma Ana Mena - Se Iluminaba",
  "David Civera - Que La Detengan",
  "Ladilla Rusa - KITT y los Coches del Pasado",
  "Nino Bravo - Un Beso y Una Flor",
  "Antonio Flores - No Dudaría",
  "Marisol - Tengo el Corazón Contento",
  "Becky G Bad Bunny - Mayores",
  "Paloma San Basilio - Juntos",
  "Melendi - Caminando por la Vida",
  "Bonnie Tyler - Holding Out For A Hero",
  "Sabrina - Boys Summertime Love",
  "Al Bano Romina Power - Felicità",
  "J Balvin - Ginza",
  "Hombres G - Venezia",
  "Duncan Dhu - En Algún Lugar",
  "Madonna - Into The Groove",
  "El Barrio - Pa Madrid",
  "Michael Sembello - Maniac",
  "Jarabe de Palo - La Flaca",
  "Nicki Minaj - Starships",
  "Julio Iglesias - Quijote",
  "Viceversa - Tu Piel Morena",
  "Olé Olé - Voy a Mil",
  "Jose De Rico Henry Mendez - Rayos de Sol",
  "SNAP! - Rhythm Is A Dancer",
  "Whigfield - Saturday Night",
  "Don Omar Lucenzo - Danza Kuduro",
  "Ricchi e Poveri - Será Porque Te Amo",
  "Nena Daconte - Tenía Tanto Que Darte",
  "Justin Bieber - Baby ft Ludacris",
  "Lolita - Sarandonga",
  "Olé Olé - No Controles",
  "Paulina Rubio - Ni Una Sola Palabra",
  "Shakira - Loba",
  "Madonna - Hung Up",
  "La Oreja de Van Gogh - Puedes Contar Conmigo",
  "Andy y Lucas - Son de Amores",
  "Cyndi Lauper - Girls Just Want To Have Fun",
  "Estopa - Cacho a Cacho",
  "ABBA - Dancing Queen",
  "La Quinta Estación - Me Muero",
  "El Canto del Loco - Besos",
  "La Bouche - Sweet Dreams",
  "Bon Jovi - It's My Life",
  "Carlos Baute Marta Sánchez - Colgando en Tus Manos",
  "Katy Perry - Hot N Cold",
  "Camela - Cuando Zarpa el Amor",
  "Queen - I Want To Break Free",
  "Calle 13 - Atrévete Te Te",
  "Sonia y Selena - Yo Quiero Bailar",
  "Alaska y Dinarama - Cómo Pudiste Hacerme Esto a Mí",
  "Lady Gaga - Born This Way",
  "Technotronic - Pump Up The Jam",
  "Gala - Freed From Desire",
  "Billy Idol - Dancing With Myself",
  "Backstreet Boys - Everybody",
  "Michael Jackson - Billie Jean",
  "Miley Cyrus - Heart of Glass",
  "Rosalía - Despechá",
  "Mecano - Maquillaje",
  "Dua Lipa - Physical feat Troye Sivan",
] as const;

export const YOUTUBE_IDS: Partial<Record<number, string>> = {
  0: "D82WTGDPtj8",
  1: "wC_sOpQjvWE",
  2: "hDupK_0xj88",
  3: "zyON1O3mYpA",
  4: "ItvV2HyOePU",
  5: "PeDZO3ubmCI",
  6: "lVdIJkaq4p0",
  7: "F1VOvQj27js",
  8: "-5EwVjQnTBs",
  9: "qz-2YuEtlic",
  10: "6jEtJtjaaN0",
  11: "igiSw9sWYXo",
  12: "36uIku4lueA",
  13: "DiBBMRYQoGI",
  14: "YiWtA73hIrc",
  15: "Lh5xF7rk5PA",
  16: "rs_hGhUPz_0",
  17: "DCB809aSNJs",
  18: "iaUuZEarx2E",
  19: "2wMnaUqdh0k",
  20: "eNIUnslU_Xo",
  21: "P2hDHNP1De0",
  22: "Cxs4OXAt6H8",
  23: "o2tdLOK7-PE",
  24: "qBUKfQRbzuk",
  25: "0xXBwwaTzqc",
  26: "BXd-NIVqfBc",
  27: "ekHoLwskh5w",
  28: "acm6O4WwgBg",
  29: "3-qsyWcpxCI",
  30: "Bx0HTJRycSQ",
  31: "ul1oxkcpMOM",
  32: "SATyGIYqExk",
  33: "wPFrb66hjys",
  34: "qn6S3H62Jh4",
  35: "IN2IcDVPRv8",
  36: "-KAYakBQ10o",
  37: "7xrM9J5wTDE",
  38: "f4KY7gpLc1c",
  39: "dxdsvoGznYY",
  40: "jH_-t8eBMVI",
  41: "HoPYu-RluBE",
  42: "0E3N3s6gZG0",
  43: "iykhVjHHQqA",
  44: "cuRKLR2gmlQ",
  45: "X3KcUZrIomk",
  46: "d9EG3XLvioc",
  47: "kN_Cxar532k",
  48: "GacX7edHD6E",
  49: "UsZuwEFHh_4",
  50: "cgFQ8byPamg",
  51: "JSDB2PBtNvk",
  52: "As4RW0HayHM",
  53: "Q-S7uUjJHQ4",
  54: "NetwnD1Pi_k",
  55: "KELRH3gnFQ0",
  56: "91qYIJBY1js",
  57: "Xkxkm_GV6Cg",
  58: "RrpbTWVrpf8",
  59: "zkuOCtmlQo8",
  60: "ooNCbW_pllw",
  61: "qEzwCh23RKg",
  62: "CiTG-n7SuhU",
  63: "DMiREvBzGY0",
  64: "4czLj14ABsQ",
  65: "ZESyq7kvjeE",
  66: "B0BDv563-DU",
  67: "hHFFD4hMEKo",
  68: "VNrfehBJhps",
  69: "vcSztpzXwSY",
  70: "C0T9aY4QsGs",
  71: "6FmZ9RU2Dsg",
  72: "pSPDBn8adwA",
  73: "VZK_wUGqEfQ",
  74: "BOi5cupTIuw",
  75: "uLLfMJ0Ai58",
  76: "CAQkox_fFsE",
  77: "TJbaGjtvmEI",
  78: "IrMSSbfJpJU",
  79: "La_BXnIixio",
  80: "kcd7wdwn0Mw",
  81: "ZYAFBTKLV4Q",
  82: "on_5rCUHNso",
  83: "u4opl2oVnHM",
  84: "3-ejlwMoI3Q",
  85: "Bx0HTJRycSQ",
  86: "w-m8Oi63cek",
  87: "wfAZ5NYCeZ8",
  88: "pqI6HhgW00I",
  89: "gXxWwP3_TOk",
  90: "4dd0FN0V4-A",
  91: "1OPOaj3_43E",
  92: "0WEA3zHJl28",
  93: "cCCQu5ozxuM",
  94: "Wwz5I3MqKA4",
  95: "igDP_5KqF_o",
  96: "v7ngUPu0Hhk",
  97: "1eSg0FiuxUg",
  98: "lnRoRNi19Jc",
  99: "3etOnE46-J0",
};

function repararMojibake(texto: string) {
  if (!/[ÃÂ]/.test(texto)) return texto;
  try {
    const bytes = Uint8Array.from(texto, (char) => char.charCodeAt(0) & 0xff);
    return new TextDecoder("utf-8").decode(bytes);
  } catch {
    return texto;
  }
}

export function limpiarEtiqueta(raw: string) {
  return repararMojibake(raw).replace(/^\d+\.\s*/, "").trim();
}

export function construirCancion(raw: string, numero: number): Cancion {
  const limpia = limpiarEtiqueta(raw);
  const partes = limpia.split(" - ");

  if (partes.length >= 2) {
    const artista = partes[0].trim() || "Artista pendiente";
    const titulo = partes.slice(1).join(" - ").trim() || limpia;

    return {
      numero,
      titulo,
      artista,
      youtubeId: YOUTUBE_IDS[numero] ?? "",
      letra: `Placeholder de letra para ${titulo}. Sustituye este texto por tu letra real cuando la tengas.`,
    };
  }

  return {
    numero,
    titulo: limpia,
    artista: "Artista pendiente",
    youtubeId: YOUTUBE_IDS[numero] ?? "",
    letra: `Placeholder de letra para ${limpia}. Sustituye este texto por tu letra real cuando la tengas.`,
  };
}

export const canciones: Cancion[] = LISTA_CANCIONES.map((raw, numero) =>
  construirCancion(raw, numero),
);

export const LOCAL_VIDEO_FILES: Partial<Record<number, string>> = {
  0:  "unanochemas.mp4",
  1:  "laplena.mp4",
  2:  "lamarinastamorena.mp4",
  3:  "esadiva.mp4",
  4:  "unanocheconhugel.mp4",
  5:  "capazvswefoundlove.mp4",
  6:  "antesmuertaquesencilla.mp4",
  7:  "mrvain.mp4",
  8:  "mehasinvitadoabailar.mp4",
  9:  "siantestehubieraconocido.mp4",
  10: "lareina.mp4",
  11: "vivelavida.mp4",
  12: "zorra.mp4",
  13: "cuandoelmartetenga.mp4",
  14: "malamujer.mp4",
  15: "lamorocha.mp4",
  16: "gasolina.mp4",
  17: "vagabundo.mp4",
  18: "elmerengue.mp4",
  19: "cotixcoti.mp4",
  20: "nocheentera.mp4",
  21: "labilirrubina.mp4",
  22: "mariposas.mp4",
  23: "monamour.mp4",
  24: "titimepregunto.mp4",
  25: "zapatillas.mp4",
  26: "taconesrojos.mp4",
  27: "nothinggonastopnow.mp4",
  28: "pepas.mp4",
  29: "tododeti.mp4",
  30: "cuandozarpaelamor.mp4",
  31: "abretumente.mp4",
  32: "therythimontenight.mp4",
  33: "mecoleenunafiesta.mp4",
  34: "yonotepidolaluna.mp4",
  35: "cuandobrilleelesol.mp4",
  36: "hayqueveniralsur.mp4",
  37: "aquienleimporta.mp4",
  38: "vivirasiesmorirdeamor.mp4",
  39: "seiluminaba.mp4",
  40: "queladetengan.mp4",
  41: "littyloscochesdelpasado.mp4",
  42: "unbesoyunaflor.mp4",
  43: "nodudaria.mp4",
  44: "corazoncontento.mp4",
  45: "mayores.mp4",
  46: "juntos.mp4",
  47: "caminandoporlavida.mp4",
  48: "holdingoutforahero.mp4",
  49: "boys.mp4",
  50: "felicita.mp4",
  51: "ginza.mp4",
  52: "venezia.mp4",
  53: "Duncan Dhu - En Algún Lugar.mp4",
  54: "intothegrove.mp4",
  55: "pamadrid.mp4",
  56: "maniac.mp4",
  57: "laflaca.mp4",
  58: "starship.mp4",
  59: "quijote.mp4",
  60: "ella.mp4",
  61: "voyamil.mp4",
  62: "rayosdesol.mp4",
  63: "rythmisadancer.mp4",
  64: "saturdaynight.mp4",
  65: "danzakuduro.mp4",
  66: "seraporqueteamo.mp4",
  67: "teniatantoquedarte.mp4",
  68: "baby.mp4",
  69: "sarandonga.mp4",
  70: "nocontroles.mp4",
  71: "niunasolapalabra.mp4",
  72: "loba.mp4",
  73: "hungup.mp4",
  74: "puedescontarconmigo.mp4",
  75: "sondeamores.mp4",
  76: "girlsjustwanttohavefun.mp4",
  77: "cachoacacho.mp4",
  78: "dancingqueen.mp4",
  79: "memuero.mp4",
  80: "besos.mp4",
  81: "sweetdreams.mp4",
  82: "itsmylife.mp4",
  83: "colgandoentusmanos.mp4",
  84: "hotancold.mp4",
  85: "cuandozarpaelamor.mp4",
  86: "iwanttobrakefree.mp4",
  87: "atrevete-te.mp4",
  88: "yoquierobailar.mp4",
  89: "comopueddistehacermeestoami.mp4",
  90: "bornthisway.mp4",
  91: "pumpupthejam.mp4",
  92: "freedfromdesire.mp4",
  93: "dancingwithmyself.mp4",
  94: "everybody.mp4",
  95: "billiejean.mp4",
  96: "heartofglass.mp4",
  97: "despecha.mp4",
  98: "maquillaje.mp4",
  99: "physical.mp4",
};
