export type Cancion = {
  numero: number;
  titulo: string;
  artista: string;
  youtubeId: string;
  letra: string;
};

export const LISTA_CANCIONES = [
  "Jennifer Lopez - Una Noche MÃ¡s letra lyrics",
  "W Sound BeÃ©le Westcol Ovy On The Drums - La Plena video lyrics letra",
  "Figa Flawas - La Marina Sta Morena letra lyrics",
  "Melody - Esa Diva letra lyrics",
  "HUGEL - Una Noche con Hugel letra lyrics",
  "Vilu Gontero - Capaz vs We Found Love mashup lyrics letra",
  "MarÃ­a Isabel - Antes Muerta Que Sencilla letra lyrics karaoke",
  "Culture Beat - Mr. Vain lyrics letra",
  "Dani FernÃ¡ndez - Me Has Invitado a Bailar letra lyrics",
  "KAROL G - Si Antes Te Hubiera Conocido letra lyrics",
  "Lola Indigo - La Reina letra lyrics",
  "Gusanito - Vive La Vida letra lyrics",
  "Nebulossa - Zorra letra lyrics",
  "El Ãšltimo de la Fila - Cuando el Mar te Tenga letra lyrics",
  "C Tangana - Mala Mujer letra lyrics",
  "Luck Ra BM - La Morocha letra lyrics",
  "Daddy Yankee - Gasolina letra lyrics karaoke",
  "SebastiÃ¡n Yatra Manuel Turizo BeÃ©le - Vagabundo letra lyrics",
  "Marshmello Manuel Turizo - El Merengue letra lyrics",
  "The Tyets - Coti x Coti lletra lyrics karaoke",
  "Vicco - Nochentera letra lyrics",
  "Juan Luis Guerra - La Bilirrubina letra lyrics karaoke",
  "sangiovanni Aitana - Mariposas letra lyrics",
  "Zzoilo Aitana - Mon Amour Remix letra lyrics",
  "Bad Bunny - TitÃ­ Me PreguntÃ³ letra lyrics",
  "El Canto del Loco - Zapatillas letra lyrics karaoke",
  "SebastiÃ¡n Yatra - Tacones Rojos letra lyrics",
  "Starship - Nothing's Gonna Stop Us Now lyrics letra karaoke",
  "Farruko - Pepas letra lyrics",
  "Rauw Alejandro - Todo de Ti letra lyrics",
  "Camela - Cuando Zarpa el Amor letra lyrics karaoke",
  "Merche - Abre Tu Mente letra lyrics",
  "Corona - The Rhythm of the Night lyrics letra",
  "Mecano - Me ColÃ© en una Fiesta letra lyrics karaoke",
  "Daniela Romo - Yo No Te Pido La Luna letra lyrics karaoke",
  "La Guardia - Cuando Brille el Sol letra lyrics",
  "Raffaella CarrÃ  - Hay Que Venir al Sur letra lyrics karaoke",
  "Alaska y Dinarama - A QuiÃ©n Le Importa letra lyrics karaoke",
  "Camilo Sesto - Vivir AsÃ­ es Morir de Amor letra lyrics karaoke",
  "Fred De Palma Ana Mena - Se Iluminaba letra lyrics",
  "David Civera - Que La Detengan letra lyrics karaoke",
  "Ladilla Rusa - KITT y los Coches del Pasado letra lyrics",
  "Nino Bravo - Un Beso y Una Flor letra lyrics karaoke",
  "Antonio Flores - No DudarÃ­a letra lyrics",
  "Marisol - Tengo el CorazÃ³n Contento letra lyrics karaoke",
  "Becky G Bad Bunny - Mayores letra lyrics",
  "Paloma San Basilio - Juntos letra lyrics karaoke",
  "Melendi - Caminando por la Vida letra lyrics",
  "Bonnie Tyler - Holding Out For A Hero lyrics letra karaoke",
  "Sabrina - Boys Summertime Love lyrics letra",
  "Al Bano Romina Power - FelicitÃ  lyrics letra karaoke",
  "J Balvin - Ginza letra lyrics",
  "Hombres G - Venezia letra lyrics karaoke",
  "Duncan Dhu - En AlgÃºn Lugar letra lyrics",
  "Madonna - Into The Groove lyrics letra",
  "El Barrio - Pa Madrid letra lyrics",
  "Michael Sembello - Maniac lyrics letra karaoke",
  "Jarabe de Palo - La Flaca letra lyrics karaoke",
  "Nicki Minaj - Starships lyrics letra",
  "Julio Iglesias - Quijote letra lyrics",
  "Viceversa - Tu Piel Morena letra lyrics",
  "OlÃ© OlÃ© - Voy a Mil letra lyrics",
  "Jose De Rico Henry Mendez - Rayos de Sol letra lyrics",
  "SNAP! - Rhythm Is A Dancer lyrics letra",
  "Whigfield - Saturday Night lyrics letra karaoke",
  "Don Omar Lucenzo - Danza Kuduro letra lyrics karaoke",
  "Ricchi e Poveri - SerÃ¡ Porque Te Amo letra lyrics karaoke",
  "Nena Daconte - TenÃ­a Tanto Que Darte letra lyrics",
  "Justin Bieber - Baby ft Ludacris lyrics letra",
  "Lolita - Sarandonga letra lyrics karaoke",
  "OlÃ© OlÃ© - No Controles letra lyrics",
  "Paulina Rubio - Ni Una Sola Palabra letra lyrics karaoke",
  "Shakira - Loba letra lyrics",
  "Madonna - Hung Up lyrics letra",
  "La Oreja de Van Gogh - Puedes Contar Conmigo letra lyrics",
  "Andy y Lucas - Son de Amores letra lyrics karaoke",
  "Cyndi Lauper - Girls Just Want To Have Fun lyrics letra",
  "Estopa - Cacho a Cacho letra lyrics",
  "ABBA - Dancing Queen lyrics letra karaoke",
  "La Quinta EstaciÃ³n - Me Muero letra lyrics",
  "El Canto del Loco - Besos letra lyrics karaoke",
  "La Bouche - Sweet Dreams lyrics letra",
  "Bon Jovi - It's My Life lyrics letra karaoke",
  "Carlos Baute Marta SÃ¡nchez - Colgando en Tus Manos letra lyrics karaoke",
  "Katy Perry - Hot N Cold lyrics letra",
  "Camela - Cuando Zarpa el Amor letra lyrics karaoke",
  "Queen - I Want To Break Free lyrics letra karaoke",
  "Calle 13 - AtrÃ©vete Te Te letra lyrics karaoke",
  "Sonia y Selena - Yo Quiero Bailar letra lyrics karaoke",
  "Alaska y Dinarama - CÃ³mo Pudiste Hacerme Esto a MÃ­ letra lyrics",
  "Lady Gaga - Born This Way lyrics letra",
  "Technotronic - Pump Up The Jam lyrics letra",
  "Gala - Freed From Desire lyrics letra",
  "Billy Idol - Dancing With Myself lyrics letra",
  "Backstreet Boys - Everybody lyrics letra karaoke",
  "Michael Jackson - Billie Jean letra lyrics karaoke",
  "Miley Cyrus - Heart of Glass lyrics letra",
  "RosalÃ­a - DespechÃ¡ letra lyrics",
  "Mecano - Maquillaje letra lyrics karaoke",
  "Dua Lipa - Physical feat Troye Sivan lyrics letra",
] as const;

export const YOUTUBE_IDS: Partial<Record<number, string>> = {
  0: "D82WTGDPtj8",
  1: "wC_sOpQjvWE",
  2: "hDupK_0xj88",
  3: "zyON1O3mYpA",
  4: "ItvV2HyOePU",
  5: "PeDZO3ubmCI",
  6: "lVdIJkaq4p0",
  7: "F1VOvQj27js",
  8: "-5EwVjQnTBs",
  9: "qz-2YuEtlic",
  10: "6jEtJtjaaN0",
  11: "igiSw9sWYXo",
  12: "36uIku4lueA",
  13: "DiBBMRYQoGI",
  14: "YiWtA73hIrc",
  15: "Lh5xF7rk5PA",
  16: "rs_hGhUPz_0",
  17: "DCB809aSNJs",
  18: "iaUuZEarx2E",
  19: "2wMnaUqdh0k",
  20: "eNIUnslU_Xo",
  21: "P2hDHNP1De0",
  22: "Cxs4OXAt6H8",
  23: "o2tdLOK7-PE",
  24: "qBUKfQRbzuk",
  25: "0xXBwwaTzqc",
  26: "BXd-NIVqfBc",
  27: "ekHoLwskh5w",
  28: "acm6O4WwgBg",
  29: "3-qsyWcpxCI",
  30: "Bx0HTJRycSQ",
  31: "ul1oxkcpMOM",
  32: "SATyGIYqExk",
  33: "wPFrb66hjys",
  34: "qn6S3H62Jh4",
  35: "IN2IcDVPRv8",
  36: "-KAYakBQ10o",
  37: "7xrM9J5wTDE",
  38: "f4KY7gpLc1c",
  39: "dxdsvoGznYY",
  40: "jH_-t8eBMVI",
  41: "HoPYu-RluBE",
  42: "0E3N3s6gZG0",
  43: "iykhVjHHQqA",
  44: "cuRKLR2gmlQ",
  45: "X3KcUZrIomk",
  46: "d9EG3XLvioc",
  47: "kN_Cxar532k",
  48: "GacX7edHD6E",
  49: "UsZuwEFHh_4",
  50: "cgFQ8byPamg",
  51: "JSDB2PBtNvk",
  52: "As4RW0HayHM",
  53: "Q-S7uUjJHQ4",
  54: "NetwnD1Pi_k",
  55: "KELRH3gnFQ0",
  56: "91qYIJBY1js",
  57: "Xkxkm_GV6Cg",
  58: "RrpbTWVrpf8",
  59: "zkuOCtmlQo8",
  60: "ooNCbW_pllw",
  61: "qEzwCh23RKg",
  62: "CiTG-n7SuhU",
  63: "DMiREvBzGY0",
  64: "4czLj14ABsQ",
  65: "ZESyq7kvjeE",
  66: "B0BDv563-DU",
  67: "hHFFD4hMEKo",
  68: "VNrfehBJhps",
  69: "vcSztpzXwSY",
  70: "C0T9aY4QsGs",
  71: "6FmZ9RU2Dsg",
  72: "pSPDBn8adwA",
  73: "VZK_wUGqEfQ",
  74: "BOi5cupTIuw",
  75: "uLLfMJ0Ai58",
  76: "CAQkox_fFsE",
  77: "TJbaGjtvmEI",
  78: "IrMSSbfJpJU",
  79: "La_BXnIixio",
  80: "kcd7wdwn0Mw",
  81: "ZYAFBTKLV4Q",
  82: "on_5rCUHNso",
  83: "u4opl2oVnHM",
  84: "3-ejlwMoI3Q",
  85: "Bx0HTJRycSQ",
  86: "w-m8Oi63cek",
  87: "wfAZ5NYCeZ8",
  88: "pqI6HhgW00I",
  89: "gXxWwP3_TOk",
  90: "4dd0FN0V4-A",
  91: "1OPOaj3_43E",
  92: "0WEA3zHJl28",
  93: "cCCQu5ozxuM",
  94: "Wwz5I3MqKA4",
  95: "igDP_5KqF_o",
  96: "v7ngUPu0Hhk",
  97: "1eSg0FiuxUg",
  98: "lnRoRNi19Jc",
  99: "3etOnE46-J0",
};

function repararMojibake(texto: string) {
  try {
    const bytes = Uint8Array.from(texto, (char) => char.charCodeAt(0) & 0xff);
    return new TextDecoder("utf-8").decode(bytes);
  } catch {
    return texto;
  }
}

export function limpiarEtiqueta(raw: string) {
  return repararMojibake(raw).replace(/^\d+\.\s*/, "").trim();
}

export function construirCancion(raw: string, numero: number): Cancion {
  const limpia = limpiarEtiqueta(raw);
  const partes = limpia.split(" - ");

  if (partes.length >= 2) {
    const artista = partes[0].trim() || "Artista pendiente";
    const titulo = partes.slice(1).join(" - ").trim() || limpia;

    return {
      numero,
      titulo,
      artista,
      youtubeId: YOUTUBE_IDS[numero] ?? "",
      letra: `Placeholder de letra para ${titulo}. Sustituye este texto por tu letra real cuando la tengas.`,
    };
  }

  return {
    numero,
    titulo: limpia,
    artista: "Artista pendiente",
    youtubeId: YOUTUBE_IDS[numero] ?? "",
    letra: `Placeholder de letra para ${limpia}. Sustituye este texto por tu letra real cuando la tengas.`,
  };
}

export const canciones: Cancion[] = LISTA_CANCIONES.map((raw, numero) =>
  construirCancion(raw, numero),
);
